config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users

  resources :items
  # get    '/items', to: 'items#index'
  # get    '/items/:id', to: 'items#show'
  # get    '/items/new', to: 'items#new
  # get    '/items/:id/edit', to: 'items#edit
  # post   '/items', to: 'items#create
  # patch  '/items/:id', to: 'items#update'
  # delete '/items/:id', to: 'items#destroy'

  get 'print', to: 'work_process#print'
  get '/drylaminate', to: 'work_process#drylaminate'
  get '/exlaminate', to: 'work_process#exlaminate'
  get '/slit', to: 'work_process#slit'
  get '/bagmake', to: 'work_process#bagmake'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# Base ApplicationRecord Class
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :productname, presence: true, length: { maximum: 30 }
  
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 },
                   uniqueness: { scope: :user_id}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }


  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true


  class << self
    # 渡された文字列のハッシュ値を返す
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # ランダムなトークンを返す
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def show
    @item = item.find(params[:id])
  end
  
  def new
    @item = Item.new
  end

  def create
    @item = items.new(item_params)
    if @item.save
      flash[:success] = "「#{@item.productname}」を登録しました。"
      # redirect_to items_url
      redirect_to @item
    else
      render 'item/new'
    end
  end

  def index
    @items = current_user.items.paginate(page: params[:page])
  end
  
  def edit
    @item = Item.find(params[:id])
    # @item = current_user.items.find(params[:id])
  end

  def update
    @item.update!(item_params)
    flash[:success] = "「#{@item.productname}」を編集しました。"
    redirect_to items_url
  end

  def destroy
    @item = Item.find(params[:id])
    item.destroy
    flash[:success] = "「#{@item}」を削除しました。"
    redirect_to items_url
  end

    # item = Item.find(params[:id])
    # if item.item_id == current_user.id
    # item.destroy
    # end
    # Item.current_user.items.find(params[:id]).destroy
    
  private

    def item_params
      params.require(:item).permit(:productname, :order_number,
                                   :product_date, :delivery_date,
                                   :delivery_number, :quantity,
                                   :process, :remarks)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # ユーザーログイン後にユーザー情報のページにリダイレクトする
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = '無効な電子メール/パスワードの組み合わせ'
      # エラーメッセージ
    render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # 保存の成功をここで扱う
      log_in @user
      flash[:success] = "登録が完了！"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # 更新に成功した場合を扱う。
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
    end

    # beforeアクション

    # ログイン済みユーザーかどうか確認
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/controllers/work_process_controller.rb
class WorkProcessController < ApplicationController
  def print
  end

  def drylaminate
  end

  def exlaminate
  end

  def slit
  end

  def bagmake
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # ページごとの完全なタイトルを返します。
  def full_title(page_title = '')
    base_title = "work App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # ユーザーのセッションを永続的にする
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # 記憶トークン (cookie) に対応するユーザーを返す
  def current_user?(user)
    user == current_user
  end

  # 現在ログイン中のユーザーを返す (いる場合)
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 永続的セッションを破棄する
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # 記憶したURL (もしくはデフォルト値) にリダイレクト
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # アクセスしようとしたURLを覚えておく
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # 渡されたユーザーのGravatar画像を返す
  def gravatar_for(user, options = { size: 80 })
    size         = options[:size]
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/work_process_helper.rb
module WorkProcessHelper
end

app/views/items/_form_items.html.erb
<%= form_with(model: @item, local: true) do |f| %>
  <%= render 'items_text/error_messages_items', object: @item %>

  <%= f.label :productname, "製品名" %>
  <%= f.text_field :productname, class: 'form-control' %>

  <%= f.label :order_number, "注番" %>
  <%= f.text_field :order_number, :placeholder => "B20001",
                                   class: 'form-control' %>

  <%= f.label :product_date, "製造日", class: 'control-label' %>
  <%= f.date_field :created_at, class: 'form-control' %>

  <%= f.label :delivery_date, "納期", class: 'control-label' %>
  <%= f.date_field :created_at, class: 'form-control' %>

  <%= f.label :quantity, "手配数量" %>
  <%= f.text_field :quantity, :placeholder => "2000m・4000m・8000m・12000m",
                               class: 'form-control' %>
  <div class= "form-group">
    <%= f.label :process, "工程", class: 'control-label' %>
    <%= f.select :process, ["印刷・ラミネート・スリット", "印刷・スリット",
                            "印刷・ラミネート・製袋",
                            "印刷・ラミネート・スリット・製袋"],
                            include_blank: "選択してください",
                            class: 'form-control', required: true %>
  </div>

  <%= f.label :remarks, "備考" %>
  <%= f.text_field :remarks, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/items/_item.html.erb
</li>
  <table class= "table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">製造名</th>
        <th scope="col">注番</th>
        <th scope="col">製造日</th>
        <th scope="col">納期</th>
        <th scope="col">手配数量</th>
        <th scope="col">工程</th>
        <th scope="col">備考</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">1</th>
        <td><%= link_to item.productname, item %></td>
        <td><%= link_to item.order_number, item %></td>
        <td><%= link_to item.product_date, item %></td>
        <td><%= link_to item.delivery_date, item %></td>
        <td><%= link_to item.quantity, item %></td>
        <td><%= link_to item.process, item %></td>
        <td><%= link_to item.remarks, item %></td>
      </tr>
    </tbody>
  </table>
  <%= link_to "編集", edit_item_path(item.id), class: "btn btn-primary" %>
  <%= link_to "削除", item_path(item), method: :delete,
                            data: { confirm: "#{item.productname}」を削除します。よろしいですか？" },
                            class: 'btn btn-danger' %>
</li>

app/views/items/edit.html.erb
<% provide(:title, '製品編集') %>
<% provide(:button_text, '製品変更登録') %>
<h1>製品編集画面</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form_items' %>
  </div>
</div>

app/views/items/index.html.erb
<% provide(:title, 'All items') %>
<h1>全ての製品</h1>

<%= will_paginate %>

<ul class="items">
  <%= render @items %>
</ul>

<%= will_paginate %>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <li><%= link_to "印刷", print_path %></li>
  </li>
  <li class="nav-item">
    <li><%= link_to "ドライラミネート", drylaminate_path %></li>
  </li>
  <li class="nav-item">
    <li><%= link_to "押出しラミネート", exlaminate_path %></li>
  </li>
  <li class="nav-item">
    <li><%= link_to "スリット", slit_path %></li>
  </li>
  <li class="nav-item">
    <li><%= link_to "製袋", bagmake_path %></li>
  </li>
</ul>

<%= link_to "新規登録", new_item_path, class: "btn btn-primary" %>

app/views/items/new.html.erb
<% provide(:title, '製品登録') %>
<% provide(:button_text, '製品登録') %>
<h1>製品登録画面</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form_items' %>
  </div>
</div>

app/views/items/show.html.erb
<% provide(:title, @item.productname) %>
<nav class="row justify-content-end">
  <div class="col-md-4">
    <table class= "table table table-hover">
      <tbody>
        <tr>
          <th><%= @item.productname %></th>
          <td><%= @item.productname %></td>
          <th><%= @item.order_number %></th>
          <th><%= @item.product_date %></th>
          <th><%= @item.delivery_date %></th>
          <th><%= @item.quantity %></th>
          <th><%= @item.process %></th>
          <th><%= @item.remarks %></th>
          <th><%= @item.created_at %>
          <td><%= @item.updated_at %>
          <%= link_to "編集", edit_item_path, class: "btn btn-primary" %>
          <%= link_to "削除", @item, method: :delete,
                            data: { confirm: "「#{@item.productname}」を削除します。よろしいですか？" },
                            class: 'btn btn-danger' %>
        </tr>    
      </tbody>
    </table>
  </div>
</nav>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <li><%= link_to "印刷", print_path %></li>
  </li>
  <li class="nav-item">
    <li><%= link_to "ドライラミネート", drylaminate_path %></li>
  </li>
  <li class="nav-item">
    <li><%= link_to "押出しラミネート", exlaminate_path %></li>
  </li>
  <li class="nav-item">
    <li><%= link_to "スリット", slit_path %></li>
  </li>
  <li class="nav-item">
    <li><%= link_to "製袋", bagmake_path %></li>
  </li>
</ul>

app/views/items_text/_error_messages_items.html.erb
<% if @item.errors.any? %>  
  <div id="error_explanation">
    <div class="alert alert-danger">
      このフォームには <%= pluralize(@item.errors.count, "error") %>.
    </div>
    <ul>
    <% @item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class= "footer-list">
  <nav>
    <ul>
      <li><%= link_to "アプリについて", about_path %></li>
      <li><a href="#">githubコード</a></li>
      <li><a href="#">自己紹介</a></li>
      <li><%= link_to "問い合わせ", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_head.html.erb
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta charset= "utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= csrf_meta_tags %>
  <%= stylesheet_pack_tag 'application',
                          'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application',
                          'data-turbolinks-track': 'reload' %>                        
</head>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-dark bg-dark"> 
  <div class="container">
    <%= link_to "Process Management", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-expand-lg navbar-right">
        <li><%= link_to "ホーム", root_path %></li>
        <li><%= link_to "ヘルプ", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "ユーザー", users_path %></li>
          <li><%= link_to "製品", items_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "プロフィール", current_user %></li>
              <li><%= link_to "設定", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>
    

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <%= render 'layouts/head' %>
  <%= render 'layouts/shim' %>
  <body>
    <%= render 'layouts/header' %>
    <div class= "container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>  
  <div id="error_explanation">
    <div class="alert alert-danger">
      このフォームには <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "about") %>
<h1>工程管理アプリに関して</h1>
  <p>何故このアプリを作ったか</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>問い合わせは</h1>
  <p>名前、メールアドレス、内容を送信できるフォームを作る予定</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>工程管理アプリヘルプ</h1>
  <p>使い方</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron jumbotron-fluid">
  <h1>Process Management</h1>
  <h2>製品を登録して納期の進捗を管理できるアプリになります。</h2>
  
  <p>まずは新規登録へ！</p>
  <%= link_to "新規登録", signup_path, class: "btn btn-primary" %>

  <p>ログインはこちらへ！</p>
  <%= link_to "ログイン", login_path, class: "btn btn-primary" %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

<div class= "form-group">
  <%= f.label :name, "名前" %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email, "メールアドレス" %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password, "パスワード" %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "パスワード確認" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
</div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank" rel="noopener noreferrer">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>全てのユーザー</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, '新規登録') %>
<% provide(:button_text, 'アカウント作成') %>
<h1>新規登録</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <%= link_to "新規登録", new_item_path, class: "btn btn-primary" %>
  <%= link_to "製品一覧", item_path, class: "btn btn-primary" %>
</div>

app/views/work_process/bagmake.html.erb
<% provide(:title, 'bagmake') %>
<h1>作業工程　製袋</h1>
<p>Find me in app/views/work_process/bagmake.html.erb</p>

app/views/work_process/drylaminate.html.erb
<% provide(:title, 'drylaminate') %>
<h1>作業工程　ドライラミネート</h1>
<p>Find me in app/views/work_process/drylaminate.html.erb</p>

app/views/work_process/exlaminate.html.erb
<% provide(:title, 'exlaminate') %>
<h1>作業工程　押出しラミネート</h1>
<p>Find me in app/views/work_process/exlaminate.html.erb</p>

app/views/work_process/print.html.erb
<% provide(:title, 'print') %>
<h1>作業工程　印刷</h1>

app/views/work_process/slit.html.erb
<% provide(:title, 'slit') %>
<h1>作業工程　スリット</h1>
<p>Find me in app/views/work_process/slit.html.erb</p>